export const CARREGA_PRODUTO_START = "CARREGA_PRODUTO_START";
export const CARREGA_PRODUTO_SUCCESS = "CARREGA_PRODUTO_SUCCESS";
export const CARREGA_PRODUTO_FAILURE = "CARREGA_PRODUTO_FAILURE";
export const LIKE_PRODUTO_START = "LIKE_PRODUTO_START";
export const LIKE_PRODUTO_SUCCESS = "LIKE_PRODUTO_SUCCESS";
export const LIKE_PRODUTO_FAILURE = "LIKE_PRODUTO_FAILURE";
export const ADICIONAR_PRODUTO_AO_CARRINHO = "ADICIONAR_PRODUTO_AO_CARRINHO";
export const ADICIONAR_PRODUTO_AO_CARRINHO_START = "ADICIONAR_PRODUTO_AO_CARRINHO_START";
export const ADICIONAR_PRODUTO_AO_CARRINHO_SUCCESS = "ADICIONAR_PRODUTO_AO_CARRINHO_SUCCESS";
export const REMOVER_PRODUTO_DO_CARRINHO= "REMOVER_PRODUTO_DO_CARRINHO";
export const REMOVER_PRODUTO_DO_CARRINHO_START = "REMOVER_PRODUTO_DO_CARRINHO_START";
export const REMOVER_PRODUTO_DO_CARRINHO_SUCCESS = "REMOVER_PRODUTO_DO_CARRINHO_SUCCESS";

